# Generated by Django 3.2.6 on 2021-12-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=50)),
                ('descrition', models.TextField(blank=True, max_length=250)),
                ('productLogo', models.CharField(blank=True, max_length=500)),
                ('productLogoAlt', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('creator', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateBy', models.CharField(max_length=20)),
                ('lastUpdatedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imageUrl', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('creator', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateBy', models.CharField(max_length=20)),
                ('lastUpdatedTime', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spechDetails', to='product_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductKeySpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('creator', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateBy', models.CharField(max_length=20)),
                ('lastUpdatedTime', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keySpechs', to='product_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailSpecsDtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imageUrl', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('creator', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateBy', models.CharField(max_length=20)),
                ('lastUpdatedTime', models.DateTimeField(auto_now=True)),
                ('ProductDetailSpecs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product_app.productdetailspecs')),
            ],
        ),
    ]
